### ISSUE TITLE
Please Support laravel 8.

### ISSUE THREAD

**Issue by alr2413** [code-lts/Laravel-FCM#11] opened 2020-11-24 08:30 UTC
Here is the composer log:

```
Problem 1
    - Root composer.json requires code-lts/laravel-fcm ^1.5 -> satisfiable by code-lts/laravel-fcm[1.5.0].
    - Conclusion: don't install laravel/framework v8.15.0 (conflict analysis result)
    - code-lts/laravel-fcm 1.5.0 requires illuminate/support 5.* || ^6 || ^7 -> satisfiable by illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.15.0, 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^8.15 -> satisfiable by laravel/framework[v8.15.0, 8.x-dev].

```

**Comment by williamdes** [comment] 2020-11-24 13:08
Duplicate of #8

**Comment by williamdes** [comment] 2020-11-24 13:09
Hi !
Please have a look to https://github.com/code-lts/Laravel-FCM/issues/8#issuecomment-703908098
And let me know as soon as possible so I can release the next version

**Closed as completed by williamdes** 2020-11-24 13:09 UTC
Labels: bug, duplicate
